defaults:
  seed_list: [11,13,17,19,23]
  model_list: ["meta-llama/Llama-2-7b-chat-hf", "HuggingFaceH4/zephyr-7b-beta"]
  methods: ["SC-PSPO", "DPO", "DiscoPOP", "GDPO", "BPPO"]
  datasets:
    argilla/dpo-mix-7k: all
    argilla/reddit_tldr_pref_5votes: all
    argilla/human_harmless_500: all
training:
  epochs: 2
  per_device_train_batch: 16
  grad_accum: 4
  lr: 5e-7
  alpha_lr: 5e-4
evaluation:
  mt_bench_prompts: true
  alpaca_eval: true
  calibration_bins: 15
